package Libraries;

public enum Tool {
	POINTER,GLabel,
	UCPROCESS, UCACTOR, UCREALATION, UCGENERAL, UCBOUNDARY, UCINCLUDE, UCEXTEND,
	SEROLE, SEACTIVATION, SENEWACTIVATION, SEDESTROYACTIVATION, SESELFACTIVATION,
	CASSOCIATION,CABSTRACT,CAGGREGATION,CLASS,CCOMPOSITION,CDEPENDENCY,CINHERITANCE,CINTERFACE,
	STATESTART,STATEFINAL,STATEHISTORY,STATE,SUBSTATE,STATETRANSITION,
	AACTION,AEDGE,AENDNODE,AINITNODE,AREGION,ATIME,
	COARTEFACT,COCOMPONENT,CODEPEND,COLIBRARY,COPACKAGE,COSCOMPONENT,
	DCOMPONENT,DDATABASE,DDEVICE,DFILE,DPROTOCAL,DSOFTWARE,DSYSTEM;
}
