package Libraries;

public enum Tool {
	POINTER,GLabel,
	UCPROCESS, UCACTOR, UCREALATION, UCGENERAL, UCBOUNDARY, UCINCLUDE, UCEXTEND,
	SEROLE, SEACTIVATION, SENEWACTIVATION, SEDESTROYACTIVATION, SESELFACTIVATION,
	CASSOCIATION,CABSTRACT,CAGGREGATION,CLASS,CCOMPOSITION,CDEPENDENCY,CINHERITANCE,CINTERFACE;
}
